apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: eks-cluster-tf
  namespace: flux-system
spec:
  path: ./
  approvePlan: "auto"
  interval: 2m
  destroyResourcesOnDeletion: true
  varsFrom:
  - kind: Secret
    name: aws-credentials
  sourceRef:
    kind: GitRepository
    name: eks-cluster-gitrepo
    namespace: flux-system
